### ISSUE TITLE
Ability to specify client hostname for connection

### ISSUE THREAD

**Issue by adh** [zillow/ctds#20]
We have application that needs to pass hostname of it's real client (instead of the API server's hostname) in client_hostname of LOGINREC structure. Thus it would be helpful for cTDS to support client_hostname argument in ctds.connect() (in the same way as currently existing appname)

**Comment by joshuahlang** [comment]
I'll look into this. It would also be useful when running in a Docker container I'd imagine.

**Comment by joshuahlang** [comment]
Fixed in v1.8.0.
