### ISSUE TITLE
Powershell install script issue

### ISSUE THREAD

**Issue by poteznyKrolik** [zillow/ctds#23]
Had a little problem  on my Network running this script 
Specifically:
```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS 
secure channel."
```
https://github.com/zillow/ctds/blob/c8b603e0ceb4069ed7454b69b0e7dfa3c7f83c6c/windows/freetds-install.ps1#L2

adding 
 `[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls`
Here: https://github.com/zillow/ctds/blob/c8b603e0ceb4069ed7454b69b0e7dfa3c7f83c6c/windows/freetds-install.ps1#L2
 or some similar should help, as it did for me. 
 
Thanks!!

**Comment by poteznyKrolik** [comment]
Additionally in this script: I didn't have CMake/NMake installed/aliased for use here in my reasonably current Powershell setup, may want to adjust for that as well. If I get time I'll put something in here.

**Comment by joshuahlang** [comment]
Interesting. I'll update the script to be explicit about the TLS version.

**Comment by nickolay** [comment]
Seems this was fixed in https://github.com/zillow/ctds/commit/78d0853114272cac2781213ef4409babf24398d5
