### ISSUE TITLE
DLL load failed: import _tds

### ISSUE THREAD

**Issue by gizmo93** [zillow/ctds#24]
Hey,

i installed ctds according to the docs https://zillow.github.io/ctds/install.html#installing-freetds on Windows 10.

> pip install --global-option=build_ext \
>     --global-option="--include-dirs=$(pwd)/include" \
>     --global-option=build_ext \
>     --global-option="--library-dirs=$(pwd)/lib" \
>     --global-option=build_ext --global-option="--rpath=./lib" \
>     ctds 

brougt error messages, so i copied the files from build/include and build/lib to \AppData\Local\Programs\Python\Python35\lib and include and after that, the installation via pip install ctds worked.

However when i try import ctds i get:

> 
> Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import ctds
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\holmo\AppData\Local\Programs\Python\Python35\lib\site-packages\ctds\__init__.py", line 8, in <module>
>     from _tds import (
> ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

After looking to site-packages\ctds i saw there are the following files:

\pool\__init__.py
__init__.py

no _tdc,py.

So i tried using the "setup.py install" inside ctds-master and i now got a ctds-1.7.0-py3.5-win-amd64.egg subfolder inside my site-packages, which includes:

ctds with __init__.py and pool subfolder
_tds.cp35-win_amd64.pyd
_tds.py

however, import ctds still leads to:

> Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import ctds
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\holmo\AppData\Local\Programs\Python\Python35\lib\site-packages\ctds-1.7.0-py3.5-win-amd64.egg\ctds\__init__.py", line 8, in <module>
>     from _tds import (
> ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

Do you see where my mistake is here? Sadly, ctds is the only python SQL Server library which includes support for "real" bulk inserts :(

Greetings
Danny

**Comment by joshuahlang** [comment]
You'll need to compile the FreeTDS shared libraries on Windows and then copy those to the current working directory (or add them to your a location on the search path Windows uses for shared libraries).

Take a look at https://github.com/zillow/ctds/blob/master/windows/freetds-install.ps1 for help on compiling FreeTDS on Windows.

**Comment by joshuahlang** [comment]
Were you able to get this working?

**Comment by joshuahlang** [comment]
Are the FreeTDS libraries on your `PATH`? e.g. https://github.com/zillow/ctds/blob/master/appveyor/test_script.ps1#L19

**Comment by gizmo93** [comment]
Yes. The thing is: I have a _tds.cp35-win_amd64.pyd in my site-packages, which is created when installing ctds using pip with the correct environment variables with the path to the compiled freeTDS includes set (according to: https://zillow.github.io/ctds/install.html). I don't get any error message when installing it. There seems to be a problem when loading the _tds.cp35-win_amd64.pyd and I don't know where to search because i don't have any experience with C-based python libraries.

Do you have some wheel files for windows which should work?

**Comment by gizmo93** [comment]
Heyy, finally got it working: You were right, it had to do with the FreeTDS includes. I got precompiled binaries from https://ci.appveyor.com/project/FreeTDS/freetds/build/1137/job/00crybi6i68to4pp/artifacts now and now the setup.py is working.

However, i still don't know where the actual error was.

Issue can be closed :-)

Greetings
Danny

**Comment by gizmo93** [comment]
Just a quick feedback after playing around with it: The BULK inserts are wonderful! Never copied data this fast to SQL Server using Python!

**Comment by joshuahlang** [comment]
Glad to hear you got it working!
