### ISSUE TITLE
Bulk insert - Do the string encodings inside C

### ISSUE THREAD

**Issue by gizmo93** [zillow/ctds#39]
At the moment we need to convert python strings to the right encoding. Thats slow, because we need to do it in python per cell. Maybe there is a possibility to implement this inside the C code for better performance.

**Comment by joshuahlang** [comment]
I would assume that [str.encode](https://docs.python.org/3/library/stdtypes.html#str.encode) is implemented using the same API that the [CPython API provides](https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_#c.PyUnicode_Encode). Or are you suggesting something else? Can you provide a code example of what you're trying to accomplish?
