### ISSUE TITLE
Bulk insert json error

### ISSUE THREAD

**Issue by kumaar449** [zillow/ctds#47]
I am using ctds to do bulk insert where I get json array of records and I pass the json array to bulk-insert I verified all the columns are matching between json and table  I get error .

Column out of range error, with json we cannot do ctds SQL param also , any suggestion here is greatly appreciated.

**Comment by lokeshkumar449** [comment]
My sample :
connection.bulk_insert(
        'Table1',
        (
            Json array here
            { "name":"kumar"}
            
        )
    )

In table all columns are varchar

**Comment by lokeshkumar449** [comment]
DatabaseError: Column number out of range   

row_count = connection.bulk_insert(
tablename,
         [
            (content)
        ]
)

**Comment by joshuahlang** [comment]
ctds 1.8 doesn't support passing row data to `bulk_insert` as `dict` objects. You'll need to upgrade to ctds 1.9
