### ISSUE TITLE
Datetime2 inconsistant results

### ISSUE THREAD

**Issue by COngstad** [zillow/ctds#49]
It seems that the microseconds from a datetime2 column do not get converted properly and at times get rounded. 

`import ctds

sql="""select cast('2018-12-11 17:19:30.641' as datetime2),cast('2018-12-11 17:19:30.642' as datetime2),cast('2018-12-11 17:19:30.997' as datetime2)"""

con_args={'server':'localhost','port':1433,'user':'sa','xxxx':'password','xxxx':'xxx','timeout':86400}

conn=ctds.connect(**con_args)

cursor=conn.cursor()

print conn.tds_version

cursor.execute(sql)

print tuple(cursor.fetchone())`

produces the following result

`7.4
(datetime.datetime(2018, 12, 11, 17, 19, 30, 640000), datetime.datetime(2018, 12, 11, 17, 19, 30, 643000), datetime.datetime(2018, 12, 11, 17, 19, 30, 997000))`

**Comment by joshuahlang** [comment]
This is an issue I'm aware of. I had started working on supporting this [here](https://github.com/zillow/ctds/tree/datetime2-support), but just haven't had time to finish it.

**Comment by COngstad** [comment]
If you can point me in the right direction of what needs to be completed I'd be happy to try and finish this up.

**Comment by joshuahlang** [comment]
https://github.com/zillow/ctds/tree/datetime2-support

**Comment by joshuahlang** [comment]
I have a fix for this merged to master. I'll try and get a release out to pypi in the next few days.

**Comment by joshuahlang** [comment]
Fixed in 1.10.0
