### ISSUE TITLE
can not install via pip(centos 6.8)

### ISSUE THREAD

**Issue by zhaoziming** [zillow/ctds#56]
[root@abc ~]# pip3 install ctds 
Collecting ctds
  Using cached https://files.pythonhosted.org/packages/b0/70/b4523f00669dea0af5fc1b0224ce74f7e51b03e05751a9eee6f085963528/ctds-1.10.1.tar.gz
Installing collected packages: ctds
  Running setup.py install for ctds ... error
    ERROR: Complete output from command /usr/local/python3/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nbgbb_52/ctds/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g9llu3j2/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ctds
    copying src/ctds/__init__.py -> build/lib.linux-x86_64-3.6/ctds
    creating build/lib.linux-x86_64-3.6/ctds/pool
    copying src/ctds/pool/__init__.py -> build/lib.linux-x86_64-3.6/ctds/pool
    running build_ext
    building '_tds' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/ctds
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCTDS_MAJOR_VERSION=1 -DCTDS_MINOR_VERSION=10 -DCTDS_PATCH_VERSION=1 -DPY_SSIZE_T_CLEAN=1 -DMSDBLIB=1 -I/usr/local/python3/include/python3.6m -c src/ctds/pyutils.c -o build/temp.linux-x86_64-3.6/src/ctds/pyutils.o
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DCTDS_MAJOR_VERSION=1 -DCTDS_MINOR_VERSION=10 -DCTDS_PATCH_VERSION=1 -DPY_SSIZE_T_CLEAN=1 -DMSDBLIB=1 -I/usr/local/python3/include/python3.6m -c src/ctds/connection.c -o build/temp.linux-x86_64-3.6/src/ctds/connection.o
    src/ctds/connection.c: In function ‘Connection_free’:
    src/ctds/connection.c:395:43: error: ‘DBSETDBNAME’ undeclared (first use in this function)
             dbsetlname(connection->login, "", DBSETDBNAME);
                                               ^
    src/ctds/connection.c:395:43: note: each undeclared identifier is reported only once for each function it appears in
    src/ctds/connection.c: In function ‘Connection_create’:
    src/ctds/connection.c:2129:69: error: ‘DBSETDBNAME’ undeclared (first use in this function)
                     if (FAIL != dbsetlname(connection->login, database, DBSETDBNAME))
                                                                         ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/local/python3/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-nbgbb_52/ctds/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-g9llu3j2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-nbgbb_52/ctds/

**Comment by joshuahlang** [comment]
What version of FreeTDS is installed?

**Comment by zhaoziming** [comment]
version is freetds.x86_64 0.82-4.el6

**Comment by zhaoziming** [comment]
> What version of FreeTDS is installed?

version is freetds.x86_64 0.82-4.el6

**Comment by joshuahlang** [comment]
That version is very old and not supported. I'd recommend upgrading to a more recent version

**Comment by zhaoziming** [comment]
My freetds is very old
