### ISSUE TITLE
Connection Pool docs incorrect

### ISSUE THREAD

**Issue by suederade** [zillow/ctds#61]
The docs located here https://zillow.github.io/ctds/pooling.html seem to be incorrect on how to make a connection pool.

Current:
```
import ctds

pool = ctds.pool.ConnectionPool(
    ctds,
    config
)
```
This results in this error:
```
AttributeError: module 'ctds' has no attribute 'pool'
```

What only works for me is this:
```
import ctds
from ctds.pool import ConnectionPool

pool = ConnectionPool(
    ctds,
    config
)
```

**Comment by joshuahlang** [comment]
Indeed. I'll update the docs ASAP.

**Comment by suederade** [comment]
@joshuahlang Thanks! Can I ask another quick question around the pools. What actually creates the transaction? I know some of them can use `with` on the connection to create a transaction, but I'm not sure that works in this case. `pymssql` I believe makes it on an execute, but I can't seem to find in the docs where a transaction begins.

**Comment by joshuahlang** [comment]
ctds relies on SQL Server to create the transaction internally, using the [IMPLICIT_TRANSACTIONS](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-implicit-transactions-transact-sql?view=sql-server-ver15) feature. How this is utilized by ctds is documented here: https://zillow.github.io/ctds/transactions.html

**Comment by suederade** [comment]
Oh, totally glossed over the documentation to the implicit transactions. My bad!

**Comment by joshuahlang** [comment]
Fixed: https://zillow.github.io/ctds/pooling.html
