### ISSUE TITLE
Cannot access local temp table within the same connection

### ISSUE THREAD

**Issue by suederade** [zillow/ctds#63]
Within the same connection, from a connection pool, (and even using the same cursor) if I populate a local temp table (#Temp) in one `execute` call, I cannot query its results in another `execute` call. I receive an `Invalid object name` error.

```
cursor.execute(create_temp, params)
cursor.execute(select_from_temp)
```

The temp table is created by using `CREATE TABLE` and populated using `INSERT INTO`.

**Comment by HuangRicky** [comment]
are you sure you didnt close the connection, and you submitted your
transaction?

then, you may try tempdb..#Temp

**Comment by suederade** [comment]
The lines are happening one after another. I'm trying to move code from pymssql to this repo, so its previously working code and SQL queries. I can try `tempdb..#Temp`.

**Comment by HuangRicky** [comment]
tempdb is a mssql thing. you may need ti find out how to reference in other
dbms.

also need to know whether all your cursor.execute are in one transaction.
then u need to submit it first

**Comment by suederade** [comment]
I am using mssql (already using the `tempdb..#Temp` mechanic). It's using implicit transactions, so I'm not sure what would cause a transaction to end between two execute statements. I can split up the create and it will always fail to find the temp table after the first execute.

**Comment by joshuahlang** [comment]
What are your `ctds.connect()` parameters? If you set `autocommit=False`, you'll have to explicitly commit the transaction following the creation of your temp table. Likewise you you set `IMPLICIT_TRANSACTIONS` to `on`

**Comment by suederade** [comment]
I did both of those things, so I'm guessing it has something to do with the implicit transactions, so I'll dig into that and close this.

**Comment by suederade** [comment]
Also this may be a stupid question, but how do I do an `id IN :ids` type query? I can't seem to send it a list or tuple. Will wrapping each individual ID in a `SqlInt` work or do I have to do `(:ids)` and then pass it that way? I can't seem to pass it any sort of list.

**Comment by joshuahlang** [comment]
Currently sequences such as `list` and `tuple` aren't mapped to SQL types since there really isn't a logical one. I'd recommend generating the query string in python, e.g. 
```
cursor.execute(
    'SELECT * FROM MyTable WHERE MyID IN ({0})'.format(
        ','.join(str(id_) for id_ in ids)
    )
)
```

**Comment by suederade** [comment]
Ok, sounds good. Thanks!
