### ISSUE TITLE
Not able to install ctds in windows

### ISSUE THREAD

**Issue by yogesh-ezest** [zillow/ctds#65]

**Comment by HuangRicky** [comment]
you need to install dependant libraries before compile.

msg me if you need additional help

**Comment by yogesh-ezest** [comment]
@HuangRicky Thanks. I have installed both the dependencies as you mentioned. Still facing the same issue.

**Comment by HuangRicky** [comment]
you can check my repo

**Comment by yogesh-ezest** [comment]
@HuangRicky Could you please delete this issue.
