### ISSUE TITLE
Are there plans to support geometry data types?

### ISSUE THREAD

**Issue by dfox-rms** [zillow/ctds#97]
Are there plans to support `geometry` data types? When I query a table with a `geometry` column named 'SHAPE', I receive the following error: `_tds.NotSupportedError: unsupported type 240 for column "SHAPE"`

CTDS has been a very useful for my work. Thanks!

**Comment by joshuahlang** [comment]
That would require support in [FreeTDS](https://github.com/FreeTDS/freetds), which is the underlying library used by cTDS for the majority of the TDS protocol implementation. Once FreeTDS supports the type ([see here for the currently supported types](https://github.com/FreeTDS/freetds/blob/master/include/sybdb.h#L155-L227)) adding support in cTDS would be possible.

**Comment by dfox-rms** [comment]
Fair point! Thanks for clarifying the underlying issue.
